# DO NOT EDIT THIS FILE!
#
# Python module TA_Base_Core__POA generated by omniidl

import omniORB
omniORB.updateModule("TA_Base_Core__POA")

# ** 1. Stub files contributing to this module
import IManagedApplicationCorbaDef_idl
import ProcessManagementDataDefinitionsCorbaDef_idl

# ** 2. Sub-modules

# ** 3. End
