# DO NOT EDIT THIS FILE!
#
# Python module TA_Base_Core generated by omniidl

import omniORB
omniORB.updateModule("TA_Base_Core")

# ** 1. Stub files contributing to this module
import IManagedAgentCorbaDef_idl
import IManagedApplicationCorbaDef_idl
import IManagedProcessCorbaDef_idl
import IProcessManagerCorbaDef_idl
import IProcessObserverCorbaDef_idl
import IProcessSubjectCorbaDef_idl
import ISystemControllerAdminCorbaDef_idl
import ProcessManagementDataDefinitionsCorbaDef_idl

# ** 2. Sub-modules

# ** 3. End
